input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["logs-topic"]
    group_id => "log-service-group"
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
