services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ms_zookeeper
    ports:
      - "2181:2181"
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: always
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
    networks:
      - microservices-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ms_kafka_ui
    ports:
      - "8090:8090"
    restart: always
    environment:
      SERVER_PORT: 8090
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - microservices-net
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Пароль для входу в Grafana
    restart: always

  postgres-booking:
    image: postgres:18-alpine
    container_name: postgres_booking
    environment:
      POSTGRES_DB: bookings_db
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: always

  postgres-admin:
    image: postgres:18-alpine
    container_name: postgres_admin
    environment:
      POSTGRES_DB: admin_service_db
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - microservices-net
    restart: always

  postgres-inventory:
    image: postgres:18-alpine
    container_name: postgres_inventory
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    networks:
      - microservices-net
    restart: always

  postgres-payment:
    image: postgres:18-alpine
    container_name: postgres_payment
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
    ports:
      - "5438:5432"
    networks:
      - microservices-net
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: ms_redis
    ports:
      - "6379:6379"
    networks:
      - microservices-net
    restart: always

  redis-insight:
    image: redis/redisinsight:latest
    container_name: ms_redis_insight
    ports:
      - "5540:5540" # ms_redis:6379
    depends_on:
      - redis
    networks:
      - microservices-net
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.5
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -E '\"status\":\"(green|yellow)\"'" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.5
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - microservices-net
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.5
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - microservices-net
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://elasticsearch:9200 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8081:8080"
    depends_on:
      keycloak-db:
        condition: service_started
    networks:
      - microservices-net
    restart: always

  keycloak-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  config-server:
    build:
      context: .
      dockerfile: modules/config-server/Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://config-server:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

  eureka-server:
    build:
      context: .
      dockerfile: modules/eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://eureka-server:8761/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  api-gateway:
    build:
      context: .
      dockerfile: modules/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "bXkgcGVyZmVjdCBzZWNyZXQga2V5IHdpdGggYWRkaXRpb25hbCBzZWNyZXQ="
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - microservices-net

  admin-service:
    build:
      context: .
      dockerfile: modules/admin-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      postgres-admin:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

  booking-service:
    build:
      context: .
      dockerfile: modules/booking-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      kafka:
        condition: service_started
      postgres-booking:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

  inventory-service:
    build:
      context: .
      dockerfile: modules/inventory-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_started
      postgres-inventory:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - microservices-net

  notification-service:
    build:
      context: .
      dockerfile: modules/notification-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

  payment-service:
    build:
      context: .
      dockerfile: modules/payment-service/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      kafka:
        condition: service_started
      postgres-payment:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

networks:
  microservices-net:
    name: microservices-net
    driver: bridge

volumes:
  keycloak_data: