server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Gateway автоматично підключає сервіси з Eureka
          lower-case-service-id: true

      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/