server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: igor
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/