server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: igor
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

resilience4j:
  circuitbreaker:
    instances:
      itemService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      itemService:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException

  ratelimiter:
    instances:
      userService:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 1s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/