spring:
  application:
    name: booking-service
  config:
    import: "optional:configserver:http://config-server:8888"
#    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://config-server:8888