spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    registered-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8761